
(define (domain sokoban)
  (:requirements :typing )
  (:types thing location direction)
  (:predicates (move-dir ?v0 - location ?v1 - location ?v2 - direction)
	(is-nongoal ?v0 - location)
	(clear ?v0 - location)
	(is-stone ?v0 - thing)
	(at ?v0 - thing ?v1 - location)
	(is-player ?v0 - thing)
	(at-goal ?v0 - thing)
	(move ?v0 - direction)
	(is-goal ?v0 - location)
  )



	(:action do_move
		:parameters (?p - thing ?from - location ?to - location ?dir - direction)
		:precondition (and (move ?dir)
			(is-player ?p)
			(at ?p ?from)
			(clear ?to)
			(move-dir ?from ?to ?dir))
		:effect (and
			(not (at ?p ?from))
			(not (clear ?to))
			(at ?p ?to)
			(clear ?from))
	)


	(:action do_push-to-goal
		:parameters (?p - thing ?s - thing ?ppos - location ?from - location ?to - location ?dir - direction)
		:precondition (and (move ?dir)
			(is-player ?p)
			(is-stone ?s)
			(at ?p ?ppos)
			(at ?s ?from)
			(clear ?to)
			(move-dir ?ppos ?from ?dir)
			(move-dir ?from ?to ?dir)
			(is-goal ?to))
		:effect (and
			(not (at ?p ?ppos))
			(not (at ?s ?from))
			(not (clear ?to))
			(at ?p ?from)
			(at ?s ?to)
			(clear ?ppos)
			(at-goal ?s))
	)


	(:action do_push-to-nongoal
		:parameters (?p - thing ?s - thing ?ppos - location ?from - location ?to - location ?dir - direction)
		:precondition (and (move ?dir)
			(is-player ?p)
			(is-stone ?s)
			(at ?p ?ppos)
			(at ?s ?from)
			(clear ?to)
			(move-dir ?ppos ?from ?dir)
			(move-dir ?from ?to ?dir)
			(is-nongoal ?to))
		:effect (and
			(not (at ?p ?ppos))
			(not (at ?s ?from))
			(not (clear ?to))
			(at ?p ?from)
			(at ?s ?to)
			(clear ?ppos)
			(not (at-goal ?s)))
	)



  (:action macro0000
    :parameters (?dir-left - direction ?dir-up - direction ?player-01 - thing ?pos-5-3 - location ?pos-6-3 - location ?pos-6-4 - location)
    :precondition (and (at ?player-01 ?pos-6-4)
      (clear ?pos-5-3)
      (clear ?pos-6-3)
      (is-player ?player-01)
      (move ?dir-left)
      (move ?dir-up)
      (move-dir ?pos-6-3 ?pos-5-3 ?dir-left)
      (move-dir ?pos-6-4 ?pos-6-3 ?dir-up))
    :effect (and
      (not (at ?player-01 ?pos-6-4))
      (not (clear ?pos-5-3))
      (at ?player-01 ?pos-5-3)
      (clear ?pos-6-4))
  )

  (:action macro0001
    :parameters (?dir-left - direction ?dir-up - direction ?player-01 - thing ?pos-4-3 - location ?pos-5-3 - location ?pos-6-3 - location ?pos-6-4 - location)
    :precondition (and (at ?player-01 ?pos-6-4)
      (clear ?pos-4-3)
      (clear ?pos-5-3)
      (clear ?pos-6-3)
      (is-player ?player-01)
      (move ?dir-left)
      (move ?dir-up)
      (move-dir ?pos-5-3 ?pos-4-3 ?dir-left)
      (move-dir ?pos-6-3 ?pos-5-3 ?dir-left)
      (move-dir ?pos-6-4 ?pos-6-3 ?dir-up))
    :effect (and
      (not (at ?player-01 ?pos-6-4))
      (not (clear ?pos-4-3))
      (at ?player-01 ?pos-4-3)
      (clear ?pos-6-4))
  )

  (:action macro0002
    :parameters (?dir-left - direction ?dir-up - direction ?player-01 - thing ?pos-3-3 - location ?pos-4-3 - location ?pos-5-3 - location ?pos-6-3 - location ?pos-6-4 - location)
    :precondition (and (at ?player-01 ?pos-6-4)
      (clear ?pos-3-3)
      (clear ?pos-4-3)
      (clear ?pos-5-3)
      (clear ?pos-6-3)
      (is-player ?player-01)
      (move ?dir-left)
      (move ?dir-up)
      (move-dir ?pos-4-3 ?pos-3-3 ?dir-left)
      (move-dir ?pos-5-3 ?pos-4-3 ?dir-left)
      (move-dir ?pos-6-3 ?pos-5-3 ?dir-left)
      (move-dir ?pos-6-4 ?pos-6-3 ?dir-up))
    :effect (and
      (not (at ?player-01 ?pos-6-4))
      (not (clear ?pos-3-3))
      (at ?player-01 ?pos-3-3)
      (clear ?pos-6-4))
  )

  (:action macro0003
    :parameters (?dir-left - direction ?dir-up - direction ?player-01 - thing ?pos-2-3 - location ?pos-3-3 - location ?pos-4-3 - location ?pos-5-3 - location ?pos-6-3 - location ?pos-6-4 - location)
    :precondition (and (at ?player-01 ?pos-6-4)
      (clear ?pos-2-3)
      (clear ?pos-3-3)
      (clear ?pos-4-3)
      (clear ?pos-5-3)
      (clear ?pos-6-3)
      (is-player ?player-01)
      (move ?dir-left)
      (move ?dir-up)
      (move-dir ?pos-3-3 ?pos-2-3 ?dir-left)
      (move-dir ?pos-4-3 ?pos-3-3 ?dir-left)
      (move-dir ?pos-5-3 ?pos-4-3 ?dir-left)
      (move-dir ?pos-6-3 ?pos-5-3 ?dir-left)
      (move-dir ?pos-6-4 ?pos-6-3 ?dir-up))
    :effect (and
      (not (at ?player-01 ?pos-6-4))
      (not (clear ?pos-2-3))
      (at ?player-01 ?pos-2-3)
      (clear ?pos-6-4))
  )

  (:action macro0004
    :parameters (?dir-down - direction ?dir-left - direction ?dir-up - direction ?player-01 - thing ?pos-2-3 - location ?pos-2-4 - location ?pos-3-3 - location ?pos-4-3 - location ?pos-5-3 - location ?pos-6-3 - location ?pos-6-4 - location)
    :precondition (and (at ?player-01 ?pos-6-4)
      (clear ?pos-2-3)
      (clear ?pos-2-4)
      (clear ?pos-3-3)
      (clear ?pos-4-3)
      (clear ?pos-5-3)
      (clear ?pos-6-3)
      (is-player ?player-01)
      (move ?dir-down)
      (move ?dir-left)
      (move ?dir-up)
      (move-dir ?pos-2-3 ?pos-2-4 ?dir-down)
      (move-dir ?pos-3-3 ?pos-2-3 ?dir-left)
      (move-dir ?pos-4-3 ?pos-3-3 ?dir-left)
      (move-dir ?pos-5-3 ?pos-4-3 ?dir-left)
      (move-dir ?pos-6-3 ?pos-5-3 ?dir-left)
      (move-dir ?pos-6-4 ?pos-6-3 ?dir-up))
    :effect (and
      (not (at ?player-01 ?pos-6-4))
      (not (clear ?pos-2-4))
      (at ?player-01 ?pos-2-4)
      (clear ?pos-6-4))
  )

  (:action macro0005
    :parameters (?dir-down - direction ?dir-left - direction ?dir-up - direction ?player-01 - thing ?pos-2-3 - location ?pos-2-4 - location ?pos-2-5 - location ?pos-3-3 - location ?pos-4-3 - location ?pos-5-3 - location ?pos-6-3 - location ?pos-6-4 - location)
    :precondition (and (at ?player-01 ?pos-6-4)
      (clear ?pos-2-3)
      (clear ?pos-2-4)
      (clear ?pos-2-5)
      (clear ?pos-3-3)
      (clear ?pos-4-3)
      (clear ?pos-5-3)
      (clear ?pos-6-3)
      (is-player ?player-01)
      (move ?dir-down)
      (move ?dir-left)
      (move ?dir-up)
      (move-dir ?pos-2-3 ?pos-2-4 ?dir-down)
      (move-dir ?pos-2-4 ?pos-2-5 ?dir-down)
      (move-dir ?pos-3-3 ?pos-2-3 ?dir-left)
      (move-dir ?pos-4-3 ?pos-3-3 ?dir-left)
      (move-dir ?pos-5-3 ?pos-4-3 ?dir-left)
      (move-dir ?pos-6-3 ?pos-5-3 ?dir-left)
      (move-dir ?pos-6-4 ?pos-6-3 ?dir-up))
    :effect (and
      (not (at ?player-01 ?pos-6-4))
      (not (clear ?pos-2-5))
      (at ?player-01 ?pos-2-5)
      (clear ?pos-6-4))
  )

  (:action macro0006
    :parameters (?dir-down - direction ?dir-left - direction ?dir-right - direction ?dir-up - direction ?player-01 - thing ?pos-2-3 - location ?pos-2-4 - location ?pos-2-5 - location ?pos-3-3 - location ?pos-3-5 - location ?pos-4-3 - location ?pos-5-3 - location ?pos-6-3 - location ?pos-6-4 - location)
    :precondition (and (at ?player-01 ?pos-6-4)
      (clear ?pos-2-3)
      (clear ?pos-2-4)
      (clear ?pos-2-5)
      (clear ?pos-3-3)
      (clear ?pos-3-5)
      (clear ?pos-4-3)
      (clear ?pos-5-3)
      (clear ?pos-6-3)
      (is-player ?player-01)
      (move ?dir-down)
      (move ?dir-left)
      (move ?dir-right)
      (move ?dir-up)
      (move-dir ?pos-2-3 ?pos-2-4 ?dir-down)
      (move-dir ?pos-2-4 ?pos-2-5 ?dir-down)
      (move-dir ?pos-2-5 ?pos-3-5 ?dir-right)
      (move-dir ?pos-3-3 ?pos-2-3 ?dir-left)
      (move-dir ?pos-4-3 ?pos-3-3 ?dir-left)
      (move-dir ?pos-5-3 ?pos-4-3 ?dir-left)
      (move-dir ?pos-6-3 ?pos-5-3 ?dir-left)
      (move-dir ?pos-6-4 ?pos-6-3 ?dir-up))
    :effect (and
      (not (at ?player-01 ?pos-6-4))
      (not (clear ?pos-3-5))
      (at ?player-01 ?pos-3-5)
      (clear ?pos-6-4))
  )

  (:action macro0007
    :parameters (?dir-down - direction ?dir-left - direction ?dir-right - direction ?dir-up - direction ?player-01 - thing ?pos-2-3 - location ?pos-2-4 - location ?pos-2-5 - location ?pos-3-3 - location ?pos-3-5 - location ?pos-3-6 - location ?pos-4-3 - location ?pos-5-3 - location ?pos-6-3 - location ?pos-6-4 - location)
    :precondition (and (at ?player-01 ?pos-6-4)
      (clear ?pos-2-3)
      (clear ?pos-2-4)
      (clear ?pos-2-5)
      (clear ?pos-3-3)
      (clear ?pos-3-5)
      (clear ?pos-3-6)
      (clear ?pos-4-3)
      (clear ?pos-5-3)
      (clear ?pos-6-3)
      (is-player ?player-01)
      (move ?dir-down)
      (move ?dir-left)
      (move ?dir-right)
      (move ?dir-up)
      (move-dir ?pos-2-3 ?pos-2-4 ?dir-down)
      (move-dir ?pos-2-4 ?pos-2-5 ?dir-down)
      (move-dir ?pos-2-5 ?pos-3-5 ?dir-right)
      (move-dir ?pos-3-3 ?pos-2-3 ?dir-left)
      (move-dir ?pos-3-5 ?pos-3-6 ?dir-down)
      (move-dir ?pos-4-3 ?pos-3-3 ?dir-left)
      (move-dir ?pos-5-3 ?pos-4-3 ?dir-left)
      (move-dir ?pos-6-3 ?pos-5-3 ?dir-left)
      (move-dir ?pos-6-4 ?pos-6-3 ?dir-up))
    :effect (and
      (not (at ?player-01 ?pos-6-4))
      (not (clear ?pos-3-6))
      (at ?player-01 ?pos-3-6)
      (clear ?pos-6-4))
  )

  (:action macro0008
    :parameters (?dir-down - direction ?dir-left - direction ?dir-right - direction ?dir-up - direction ?player-01 - thing ?pos-2-3 - location ?pos-2-4 - location ?pos-2-5 - location ?pos-3-3 - location ?pos-3-5 - location ?pos-3-6 - location ?pos-4-3 - location ?pos-4-6 - location ?pos-5-3 - location ?pos-6-3 - location ?pos-6-4 - location)
    :precondition (and (at ?player-01 ?pos-6-4)
      (clear ?pos-2-3)
      (clear ?pos-2-4)
      (clear ?pos-2-5)
      (clear ?pos-3-3)
      (clear ?pos-3-5)
      (clear ?pos-3-6)
      (clear ?pos-4-3)
      (clear ?pos-4-6)
      (clear ?pos-5-3)
      (clear ?pos-6-3)
      (is-player ?player-01)
      (move ?dir-down)
      (move ?dir-left)
      (move ?dir-right)
      (move ?dir-up)
      (move-dir ?pos-2-3 ?pos-2-4 ?dir-down)
      (move-dir ?pos-2-4 ?pos-2-5 ?dir-down)
      (move-dir ?pos-2-5 ?pos-3-5 ?dir-right)
      (move-dir ?pos-3-3 ?pos-2-3 ?dir-left)
      (move-dir ?pos-3-5 ?pos-3-6 ?dir-down)
      (move-dir ?pos-3-6 ?pos-4-6 ?dir-right)
      (move-dir ?pos-4-3 ?pos-3-3 ?dir-left)
      (move-dir ?pos-5-3 ?pos-4-3 ?dir-left)
      (move-dir ?pos-6-3 ?pos-5-3 ?dir-left)
      (move-dir ?pos-6-4 ?pos-6-3 ?dir-up))
    :effect (and
      (not (at ?player-01 ?pos-6-4))
      (not (clear ?pos-4-6))
      (at ?player-01 ?pos-4-6)
      (clear ?pos-6-4))
  )

  (:action macro0009
    :parameters (?dir-down - direction ?dir-left - direction ?dir-right - direction ?dir-up - direction ?player-01 - thing ?pos-2-3 - location ?pos-2-4 - location ?pos-2-5 - location ?pos-3-3 - location ?pos-3-5 - location ?pos-4-3 - location ?pos-4-5 - location ?pos-5-3 - location ?pos-6-3 - location ?pos-6-4 - location)
    :precondition (and (at ?player-01 ?pos-6-4)
      (clear ?pos-2-3)
      (clear ?pos-2-4)
      (clear ?pos-2-5)
      (clear ?pos-3-3)
      (clear ?pos-3-5)
      (clear ?pos-4-3)
      (clear ?pos-4-5)
      (clear ?pos-5-3)
      (clear ?pos-6-3)
      (is-player ?player-01)
      (move ?dir-down)
      (move ?dir-left)
      (move ?dir-right)
      (move ?dir-up)
      (move-dir ?pos-2-3 ?pos-2-4 ?dir-down)
      (move-dir ?pos-2-4 ?pos-2-5 ?dir-down)
      (move-dir ?pos-2-5 ?pos-3-5 ?dir-right)
      (move-dir ?pos-3-3 ?pos-2-3 ?dir-left)
      (move-dir ?pos-3-5 ?pos-4-5 ?dir-right)
      (move-dir ?pos-4-3 ?pos-3-3 ?dir-left)
      (move-dir ?pos-5-3 ?pos-4-3 ?dir-left)
      (move-dir ?pos-6-3 ?pos-5-3 ?dir-left)
      (move-dir ?pos-6-4 ?pos-6-3 ?dir-up))
    :effect (and
      (not (at ?player-01 ?pos-6-4))
      (not (clear ?pos-4-5))
      (at ?player-01 ?pos-4-5)
      (clear ?pos-6-4))
  )

  (:action macro0010
    :parameters (?dir-left - direction ?dir-up - direction ?player-01 - thing ?pos-4-2 - location ?pos-4-3 - location ?pos-5-3 - location ?pos-6-3 - location ?pos-6-4 - location)
    :precondition (and (at ?player-01 ?pos-6-4)
      (clear ?pos-4-2)
      (clear ?pos-4-3)
      (clear ?pos-5-3)
      (clear ?pos-6-3)
      (is-player ?player-01)
      (move ?dir-left)
      (move ?dir-up)
      (move-dir ?pos-4-3 ?pos-4-2 ?dir-up)
      (move-dir ?pos-5-3 ?pos-4-3 ?dir-left)
      (move-dir ?pos-6-3 ?pos-5-3 ?dir-left)
      (move-dir ?pos-6-4 ?pos-6-3 ?dir-up))
    :effect (and
      (not (at ?player-01 ?pos-6-4))
      (not (clear ?pos-4-2))
      (at ?player-01 ?pos-4-2)
      (clear ?pos-6-4))
  )

  (:action macro0011
    :parameters (?dir-left - direction ?dir-up - direction ?player-01 - thing ?pos-3-2 - location ?pos-4-2 - location ?pos-4-3 - location ?pos-5-3 - location ?pos-6-3 - location ?pos-6-4 - location)
    :precondition (and (at ?player-01 ?pos-6-4)
      (clear ?pos-3-2)
      (clear ?pos-4-2)
      (clear ?pos-4-3)
      (clear ?pos-5-3)
      (clear ?pos-6-3)
      (is-player ?player-01)
      (move ?dir-left)
      (move ?dir-up)
      (move-dir ?pos-4-2 ?pos-3-2 ?dir-left)
      (move-dir ?pos-4-3 ?pos-4-2 ?dir-up)
      (move-dir ?pos-5-3 ?pos-4-3 ?dir-left)
      (move-dir ?pos-6-3 ?pos-5-3 ?dir-left)
      (move-dir ?pos-6-4 ?pos-6-3 ?dir-up))
    :effect (and
      (not (at ?player-01 ?pos-6-4))
      (not (clear ?pos-3-2))
      (at ?player-01 ?pos-3-2)
      (clear ?pos-6-4))
  )

  (:action macro0012
    :parameters (?dir-down - direction ?dir-left - direction ?dir-right - direction ?dir-up - direction ?player-01 - thing ?pos-2-3 - location ?pos-2-4 - location ?pos-2-5 - location ?pos-3-2 - location ?pos-3-3 - location ?pos-3-4 - location ?pos-3-5 - location ?pos-3-6 - location ?pos-4-2 - location ?pos-4-3 - location ?pos-4-4 - location ?pos-4-5 - location ?pos-4-6 - location ?pos-5-3 - location ?pos-5-4 - location ?pos-6-3 - location ?pos-6-4 - location ?stone-01 - thing ?stone-02 - thing ?stone-03 - thing)
    :precondition (and (at ?player-01 ?pos-6-4)
      (at ?stone-01 ?pos-3-4)
      (at ?stone-02 ?pos-4-4)
      (at ?stone-03 ?pos-5-4)
      (clear ?pos-2-3)
      (clear ?pos-2-4)
      (clear ?pos-2-5)
      (clear ?pos-3-2)
      (clear ?pos-3-3)
      (clear ?pos-3-5)
      (clear ?pos-3-6)
      (clear ?pos-4-2)
      (clear ?pos-4-3)
      (clear ?pos-4-5)
      (clear ?pos-4-6)
      (clear ?pos-5-3)
      (clear ?pos-6-3)
      (is-goal ?pos-2-4)
      (is-goal ?pos-3-4)
      (is-goal ?pos-4-4)
      (is-nongoal ?pos-2-3)
      (is-nongoal ?pos-3-3)
      (is-nongoal ?pos-4-5)
      (is-nongoal ?pos-5-4)
      (is-player ?player-01)
      (is-stone ?stone-01)
      (is-stone ?stone-02)
      (is-stone ?stone-03)
      (move ?dir-down)
      (move ?dir-left)
      (move ?dir-right)
      (move ?dir-up)
      (move-dir ?pos-2-3 ?pos-2-4 ?dir-down)
      (move-dir ?pos-2-4 ?pos-2-3 ?dir-up)
      (move-dir ?pos-2-4 ?pos-2-5 ?dir-down)
      (move-dir ?pos-2-4 ?pos-3-4 ?dir-right)
      (move-dir ?pos-2-5 ?pos-2-4 ?dir-up)
      (move-dir ?pos-2-5 ?pos-3-5 ?dir-right)
      (move-dir ?pos-3-2 ?pos-3-3 ?dir-down)
      (move-dir ?pos-3-3 ?pos-2-3 ?dir-left)
      (move-dir ?pos-3-3 ?pos-3-4 ?dir-down)
      (move-dir ?pos-3-3 ?pos-4-3 ?dir-right)
      (move-dir ?pos-3-4 ?pos-2-4 ?dir-left)
      (move-dir ?pos-3-4 ?pos-3-3 ?dir-up)
      (move-dir ?pos-3-4 ?pos-3-5 ?dir-down)
      (move-dir ?pos-3-4 ?pos-4-4 ?dir-right)
      (move-dir ?pos-3-5 ?pos-2-5 ?dir-left)
      (move-dir ?pos-3-5 ?pos-3-4 ?dir-up)
      (move-dir ?pos-3-5 ?pos-3-6 ?dir-down)
      (move-dir ?pos-3-6 ?pos-4-6 ?dir-right)
      (move-dir ?pos-4-2 ?pos-3-2 ?dir-left)
      (move-dir ?pos-4-3 ?pos-3-3 ?dir-left)
      (move-dir ?pos-4-3 ?pos-4-2 ?dir-up)
      (move-dir ?pos-4-3 ?pos-4-4 ?dir-down)
      (move-dir ?pos-4-3 ?pos-5-3 ?dir-right)
      (move-dir ?pos-4-4 ?pos-3-4 ?dir-left)
      (move-dir ?pos-4-4 ?pos-4-3 ?dir-up)
      (move-dir ?pos-4-4 ?pos-4-5 ?dir-down)
      (move-dir ?pos-4-4 ?pos-5-4 ?dir-right)
      (move-dir ?pos-4-5 ?pos-3-5 ?dir-left)
      (move-dir ?pos-4-5 ?pos-4-4 ?dir-up)
      (move-dir ?pos-4-6 ?pos-4-5 ?dir-up)
      (move-dir ?pos-5-3 ?pos-4-3 ?dir-left)
      (move-dir ?pos-5-3 ?pos-6-3 ?dir-right)
      (move-dir ?pos-5-4 ?pos-4-4 ?dir-left)
      (move-dir ?pos-5-4 ?pos-6-4 ?dir-right)
      (move-dir ?pos-6-3 ?pos-5-3 ?dir-left)
      (move-dir ?pos-6-3 ?pos-6-4 ?dir-down)
      (move-dir ?pos-6-4 ?pos-5-4 ?dir-left)
      (move-dir ?pos-6-4 ?pos-6-3 ?dir-up))
    :effect (and
      (not (at ?stone-03 ?pos-5-4))
      (not (clear ?pos-2-3))
      (at ?stone-03 ?pos-2-3)
      (clear ?pos-5-4))
  )

  (:action macro0013
    :parameters (?dir-down - direction ?dir-left - direction ?dir-right - direction ?dir-up - direction ?player-01 - thing ?pos-2-3 - location ?pos-2-4 - location ?pos-2-5 - location ?pos-3-2 - location ?pos-3-3 - location ?pos-3-4 - location ?pos-3-5 - location ?pos-3-6 - location ?pos-4-2 - location ?pos-4-3 - location ?pos-4-4 - location ?pos-4-5 - location ?pos-4-6 - location ?pos-5-3 - location ?pos-5-4 - location ?pos-6-3 - location ?pos-6-4 - location ?stone-01 - thing ?stone-02 - thing ?stone-03 - thing)
    :precondition (and (at ?player-01 ?pos-6-4)
      (at ?stone-01 ?pos-3-4)
      (at ?stone-02 ?pos-4-4)
      (at ?stone-03 ?pos-5-4)
      (clear ?pos-2-3)
      (clear ?pos-2-4)
      (clear ?pos-2-5)
      (clear ?pos-3-2)
      (clear ?pos-3-3)
      (clear ?pos-3-5)
      (clear ?pos-3-6)
      (clear ?pos-4-2)
      (clear ?pos-4-3)
      (clear ?pos-4-5)
      (clear ?pos-4-6)
      (clear ?pos-5-3)
      (clear ?pos-6-3)
      (is-goal ?pos-2-4)
      (is-goal ?pos-3-4)
      (is-goal ?pos-4-4)
      (is-nongoal ?pos-2-5)
      (is-nongoal ?pos-3-3)
      (is-nongoal ?pos-4-5)
      (is-nongoal ?pos-5-4)
      (is-player ?player-01)
      (is-stone ?stone-01)
      (is-stone ?stone-02)
      (is-stone ?stone-03)
      (move ?dir-down)
      (move ?dir-left)
      (move ?dir-right)
      (move ?dir-up)
      (move-dir ?pos-2-3 ?pos-2-4 ?dir-down)
      (move-dir ?pos-2-3 ?pos-3-3 ?dir-right)
      (move-dir ?pos-2-4 ?pos-2-3 ?dir-up)
      (move-dir ?pos-2-4 ?pos-2-5 ?dir-down)
      (move-dir ?pos-2-5 ?pos-3-5 ?dir-right)
      (move-dir ?pos-3-2 ?pos-3-3 ?dir-down)
      (move-dir ?pos-3-3 ?pos-2-3 ?dir-left)
      (move-dir ?pos-3-3 ?pos-3-4 ?dir-down)
      (move-dir ?pos-3-3 ?pos-4-3 ?dir-right)
      (move-dir ?pos-3-4 ?pos-2-4 ?dir-left)
      (move-dir ?pos-3-4 ?pos-3-3 ?dir-up)
      (move-dir ?pos-3-4 ?pos-3-5 ?dir-down)
      (move-dir ?pos-3-4 ?pos-4-4 ?dir-right)
      (move-dir ?pos-3-5 ?pos-3-4 ?dir-up)
      (move-dir ?pos-3-5 ?pos-3-6 ?dir-down)
      (move-dir ?pos-3-6 ?pos-4-6 ?dir-right)
      (move-dir ?pos-4-2 ?pos-3-2 ?dir-left)
      (move-dir ?pos-4-3 ?pos-3-3 ?dir-left)
      (move-dir ?pos-4-3 ?pos-4-2 ?dir-up)
      (move-dir ?pos-4-3 ?pos-4-4 ?dir-down)
      (move-dir ?pos-4-3 ?pos-5-3 ?dir-right)
      (move-dir ?pos-4-4 ?pos-3-4 ?dir-left)
      (move-dir ?pos-4-4 ?pos-4-3 ?dir-up)
      (move-dir ?pos-4-4 ?pos-4-5 ?dir-down)
      (move-dir ?pos-4-4 ?pos-5-4 ?dir-right)
      (move-dir ?pos-4-5 ?pos-3-5 ?dir-left)
      (move-dir ?pos-4-5 ?pos-4-4 ?dir-up)
      (move-dir ?pos-4-6 ?pos-4-5 ?dir-up)
      (move-dir ?pos-5-3 ?pos-4-3 ?dir-left)
      (move-dir ?pos-5-3 ?pos-6-3 ?dir-right)
      (move-dir ?pos-5-4 ?pos-4-4 ?dir-left)
      (move-dir ?pos-5-4 ?pos-6-4 ?dir-right)
      (move-dir ?pos-6-3 ?pos-5-3 ?dir-left)
      (move-dir ?pos-6-3 ?pos-6-4 ?dir-down)
      (move-dir ?pos-6-4 ?pos-5-4 ?dir-left)
      (move-dir ?pos-6-4 ?pos-6-3 ?dir-up))
    :effect (and
      (not (at ?stone-03 ?pos-5-4))
      (not (clear ?pos-2-5))
      (at ?stone-03 ?pos-2-5)
      (clear ?pos-5-4))
  )

  (:action macro0014
    :parameters (?dir-down - direction ?dir-left - direction ?dir-right - direction ?dir-up - direction ?player-01 - thing ?pos-2-4 - location ?pos-3-3 - location ?pos-3-4 - location ?pos-3-5 - location ?pos-3-6 - location ?pos-4-3 - location ?pos-4-4 - location ?pos-4-5 - location ?pos-4-6 - location ?pos-5-3 - location ?pos-6-3 - location ?pos-6-4 - location ?stone-01 - thing ?stone-02 - thing)
    :precondition (and (at ?player-01 ?pos-6-4)
      (at ?stone-01 ?pos-3-4)
      (at ?stone-02 ?pos-4-4)
      (clear ?pos-2-4)
      (clear ?pos-3-3)
      (clear ?pos-3-5)
      (clear ?pos-3-6)
      (clear ?pos-4-3)
      (clear ?pos-4-5)
      (clear ?pos-4-6)
      (clear ?pos-5-3)
      (clear ?pos-6-3)
      (is-goal ?pos-2-4)
      (is-goal ?pos-4-4)
      (is-nongoal ?pos-4-5)
      (is-player ?player-01)
      (is-stone ?stone-01)
      (is-stone ?stone-02)
      (move ?dir-down)
      (move ?dir-left)
      (move ?dir-right)
      (move ?dir-up)
      (move-dir ?pos-3-3 ?pos-4-3 ?dir-right)
      (move-dir ?pos-3-4 ?pos-2-4 ?dir-left)
      (move-dir ?pos-3-4 ?pos-3-3 ?dir-up)
      (move-dir ?pos-3-4 ?pos-3-5 ?dir-down)
      (move-dir ?pos-3-5 ?pos-3-4 ?dir-up)
      (move-dir ?pos-3-5 ?pos-3-6 ?dir-down)
      (move-dir ?pos-3-6 ?pos-4-6 ?dir-right)
      (move-dir ?pos-4-3 ?pos-4-4 ?dir-down)
      (move-dir ?pos-4-3 ?pos-5-3 ?dir-right)
      (move-dir ?pos-4-4 ?pos-3-4 ?dir-left)
      (move-dir ?pos-4-4 ?pos-4-5 ?dir-down)
      (move-dir ?pos-4-5 ?pos-3-5 ?dir-left)
      (move-dir ?pos-4-5 ?pos-4-4 ?dir-up)
      (move-dir ?pos-4-6 ?pos-4-5 ?dir-up)
      (move-dir ?pos-5-3 ?pos-4-3 ?dir-left)
      (move-dir ?pos-5-3 ?pos-6-3 ?dir-right)
      (move-dir ?pos-6-3 ?pos-5-3 ?dir-left)
      (move-dir ?pos-6-3 ?pos-6-4 ?dir-down)
      (move-dir ?pos-6-4 ?pos-6-3 ?dir-up))
    :effect (and
      (not (at ?stone-01 ?pos-3-4))
      (not (clear ?pos-2-4))
      (at ?stone-01 ?pos-2-4)
      (at-goal ?stone-01)
      (clear ?pos-3-4))
  )

  (:action macro0015
    :parameters (?dir-down - direction ?dir-left - direction ?dir-right - direction ?dir-up - direction ?player-01 - thing ?pos-2-3 - location ?pos-2-4 - location ?pos-2-5 - location ?pos-3-3 - location ?pos-3-5 - location ?pos-3-6 - location ?pos-4-3 - location ?pos-4-4 - location ?pos-4-5 - location ?pos-4-6 - location ?pos-5-3 - location ?pos-5-4 - location ?pos-6-3 - location ?pos-6-4 - location ?stone-02 - thing ?stone-03 - thing)
    :precondition (and (at ?player-01 ?pos-6-4)
      (at ?stone-02 ?pos-4-4)
      (at ?stone-03 ?pos-5-4)
      (clear ?pos-2-3)
      (clear ?pos-2-4)
      (clear ?pos-2-5)
      (clear ?pos-3-3)
      (clear ?pos-3-5)
      (clear ?pos-3-6)
      (clear ?pos-4-3)
      (clear ?pos-4-5)
      (clear ?pos-4-6)
      (clear ?pos-5-3)
      (clear ?pos-6-3)
      (is-goal ?pos-4-4)
      (is-nongoal ?pos-4-5)
      (is-nongoal ?pos-6-4)
      (is-player ?player-01)
      (is-stone ?stone-02)
      (is-stone ?stone-03)
      (move ?dir-down)
      (move ?dir-left)
      (move ?dir-right)
      (move ?dir-up)
      (move-dir ?pos-2-3 ?pos-2-4 ?dir-down)
      (move-dir ?pos-2-3 ?pos-3-3 ?dir-right)
      (move-dir ?pos-2-4 ?pos-2-3 ?dir-up)
      (move-dir ?pos-2-4 ?pos-2-5 ?dir-down)
      (move-dir ?pos-2-5 ?pos-2-4 ?dir-up)
      (move-dir ?pos-2-5 ?pos-3-5 ?dir-right)
      (move-dir ?pos-3-3 ?pos-2-3 ?dir-left)
      (move-dir ?pos-3-3 ?pos-4-3 ?dir-right)
      (move-dir ?pos-3-5 ?pos-2-5 ?dir-left)
      (move-dir ?pos-3-5 ?pos-3-6 ?dir-down)
      (move-dir ?pos-3-6 ?pos-4-6 ?dir-right)
      (move-dir ?pos-4-3 ?pos-3-3 ?dir-left)
      (move-dir ?pos-4-3 ?pos-4-4 ?dir-down)
      (move-dir ?pos-4-3 ?pos-5-3 ?dir-right)
      (move-dir ?pos-4-4 ?pos-4-3 ?dir-up)
      (move-dir ?pos-4-4 ?pos-4-5 ?dir-down)
      (move-dir ?pos-4-4 ?pos-5-4 ?dir-right)
      (move-dir ?pos-4-5 ?pos-3-5 ?dir-left)
      (move-dir ?pos-4-5 ?pos-4-4 ?dir-up)
      (move-dir ?pos-4-6 ?pos-4-5 ?dir-up)
      (move-dir ?pos-5-3 ?pos-4-3 ?dir-left)
      (move-dir ?pos-5-3 ?pos-5-4 ?dir-down)
      (move-dir ?pos-5-4 ?pos-4-4 ?dir-left)
      (move-dir ?pos-5-4 ?pos-6-4 ?dir-right)
      (move-dir ?pos-6-3 ?pos-5-3 ?dir-left)
      (move-dir ?pos-6-4 ?pos-6-3 ?dir-up))
    :effect (and
      (not (at ?player-01 ?pos-6-4))
      (not (at ?stone-03 ?pos-5-4))
      (not (at-goal ?stone-03))
      (at ?player-01 ?pos-5-4)
      (at ?stone-03 ?pos-6-4))
  )
)
