(define (domain doors)
  (:requirements :strips :typing)
  (:types location room key)
  (:predicates
     (at ?loc - location)
     (unlocked ?room - room)
     (locinroom ?loc - location ?room - room)
     (keyat ?key - key ?loc - location)
     (keyforroom ?key - key ?room - room)
     (moveto ?loc - location)
     (pick ?key - key)
  )

  (:action do_moveto
    :parameters (?sloc - location ?eloc - location ?eroom - room)
    :precondition (and (moveto ?eloc)
                       (at ?sloc)
                       (unlocked ?eroom)
                       (locinroom ?eloc ?eroom)
                  )
    :effect (and (not (at ?sloc))
                 (at ?eloc)
            )
  )

  (:action do_pick
    :parameters (?loc - location ?key - key ?room - room)
    :precondition (and (pick ?key)
                       (at ?loc)
                       (keyat ?key ?loc)
                       (keyforroom ?key ?room)
                  )
    :effect (and (not (keyat ?key ?loc))
                 (unlocked ?room)
            )
  )



  (:action macro0000
    :parameters (?key-0 - key ?loc-0-0 - location ?loc-0-3 - location ?room-0 - room ?room-1 - room)
    :precondition (and (at ?loc-0-0)
      (keyat ?key-0 ?loc-0-3)
      (keyforroom ?key-0 ?room-1)
      (locinroom ?loc-0-0 ?room-0)
      (locinroom ?loc-0-3 ?room-0)
      (moveto ?loc-0-0)
      (moveto ?loc-0-3)
      (pick ?key-0)
      (unlocked ?room-0))
    :effect (and
      (not (keyat ?key-0 ?loc-0-3))
      (unlocked ?room-1))
  )

  (:action macro0001
    :parameters (?key-0 - key ?loc-0-0 - location ?loc-0-3 - location ?room-0 - room ?room-1 - room)
    :precondition (and (at ?loc-0-0)
      (keyat ?key-0 ?loc-0-3)
      (keyforroom ?key-0 ?room-1)
      (locinroom ?loc-0-3 ?room-0)
      (moveto ?loc-0-3)
      (pick ?key-0)
      (unlocked ?room-0))
    :effect (and
      (not (at ?loc-0-0))
      (not (keyat ?key-0 ?loc-0-3))
      (at ?loc-0-3)
      (unlocked ?room-1))
  )

  (:action macro0002
    :parameters (?key-0 - key ?loc-0-0 - location ?loc-0-1 - location ?loc-0-3 - location ?room-0 - room ?room-1 - room)
    :precondition (and (at ?loc-0-0)
      (keyat ?key-0 ?loc-0-3)
      (keyforroom ?key-0 ?room-1)
      (locinroom ?loc-0-1 ?room-0)
      (locinroom ?loc-0-3 ?room-0)
      (moveto ?loc-0-1)
      (moveto ?loc-0-3)
      (pick ?key-0)
      (unlocked ?room-0))
    :effect (and
      (not (at ?loc-0-0))
      (not (keyat ?key-0 ?loc-0-3))
      (at ?loc-0-1)
      (unlocked ?room-1))
  )

  (:action macro0003
    :parameters (?key-0 - key ?loc-0-0 - location ?loc-0-2 - location ?loc-0-3 - location ?room-0 - room ?room-1 - room)
    :precondition (and (at ?loc-0-0)
      (keyat ?key-0 ?loc-0-3)
      (keyforroom ?key-0 ?room-1)
      (locinroom ?loc-0-2 ?room-0)
      (locinroom ?loc-0-3 ?room-0)
      (moveto ?loc-0-2)
      (moveto ?loc-0-3)
      (pick ?key-0)
      (unlocked ?room-0))
    :effect (and
      (not (at ?loc-0-0))
      (not (keyat ?key-0 ?loc-0-3))
      (at ?loc-0-2)
      (unlocked ?room-1))
  )

  (:action macro0004
    :parameters (?key-0 - key ?loc-0-0 - location ?loc-0-3 - location ?loc-0-4 - location ?room-0 - room ?room-1 - room)
    :precondition (and (at ?loc-0-0)
      (keyat ?key-0 ?loc-0-3)
      (keyforroom ?key-0 ?room-1)
      (locinroom ?loc-0-3 ?room-0)
      (locinroom ?loc-0-4 ?room-1)
      (moveto ?loc-0-3)
      (moveto ?loc-0-4)
      (pick ?key-0)
      (unlocked ?room-0))
    :effect (and
      (not (at ?loc-0-0))
      (not (keyat ?key-0 ?loc-0-3))
      (at ?loc-0-4)
      (unlocked ?room-1))
  )

  (:action macro0005
    :parameters (?key-0 - key ?key-1 - key ?loc-0-0 - location ?loc-0-3 - location ?loc-0-4 - location ?room-0 - room ?room-1 - room ?room-2 - room)
    :precondition (and (at ?loc-0-0)
      (keyat ?key-0 ?loc-0-3)
      (keyat ?key-1 ?loc-0-4)
      (keyforroom ?key-0 ?room-1)
      (keyforroom ?key-1 ?room-2)
      (locinroom ?loc-0-0 ?room-0)
      (locinroom ?loc-0-3 ?room-0)
      (locinroom ?loc-0-4 ?room-1)
      (moveto ?loc-0-0)
      (moveto ?loc-0-3)
      (moveto ?loc-0-4)
      (pick ?key-0)
      (pick ?key-1)
      (unlocked ?room-0))
    :effect (and
      (not (keyat ?key-0 ?loc-0-3))
      (not (keyat ?key-1 ?loc-0-4))
      (unlocked ?room-1)
      (unlocked ?room-2))
  )

  (:action macro0006
    :parameters (?key-0 - key ?loc-0-0 - location ?loc-0-3 - location ?loc-0-5 - location ?room-0 - room ?room-1 - room)
    :precondition (and (at ?loc-0-0)
      (keyat ?key-0 ?loc-0-3)
      (keyforroom ?key-0 ?room-1)
      (locinroom ?loc-0-3 ?room-0)
      (locinroom ?loc-0-5 ?room-0)
      (moveto ?loc-0-3)
      (moveto ?loc-0-5)
      (pick ?key-0)
      (unlocked ?room-0))
    :effect (and
      (not (at ?loc-0-0))
      (not (keyat ?key-0 ?loc-0-3))
      (at ?loc-0-5)
      (unlocked ?room-1))
  )

  (:action macro0007
    :parameters (?key-0 - key ?loc-0-0 - location ?loc-0-3 - location ?loc-1-0 - location ?room-0 - room ?room-1 - room)
    :precondition (and (at ?loc-0-0)
      (keyat ?key-0 ?loc-0-3)
      (keyforroom ?key-0 ?room-1)
      (locinroom ?loc-0-3 ?room-0)
      (locinroom ?loc-1-0 ?room-0)
      (moveto ?loc-0-3)
      (moveto ?loc-1-0)
      (pick ?key-0)
      (unlocked ?room-0))
    :effect (and
      (not (at ?loc-0-0))
      (not (keyat ?key-0 ?loc-0-3))
      (at ?loc-1-0)
      (unlocked ?room-1))
  )

  (:action macro0008
    :parameters (?key-0 - key ?loc-0-0 - location ?loc-0-3 - location ?loc-1-2 - location ?room-0 - room ?room-1 - room)
    :precondition (and (at ?loc-0-0)
      (keyat ?key-0 ?loc-0-3)
      (keyforroom ?key-0 ?room-1)
      (locinroom ?loc-0-3 ?room-0)
      (locinroom ?loc-1-2 ?room-0)
      (moveto ?loc-0-3)
      (moveto ?loc-1-2)
      (pick ?key-0)
      (unlocked ?room-0))
    :effect (and
      (not (at ?loc-0-0))
      (not (keyat ?key-0 ?loc-0-3))
      (at ?loc-1-2)
      (unlocked ?room-1))
  )

  (:action macro0009
    :parameters (?key-0 - key ?loc-0-0 - location ?loc-0-3 - location ?loc-1-3 - location ?room-0 - room ?room-1 - room)
    :precondition (and (at ?loc-0-0)
      (keyat ?key-0 ?loc-0-3)
      (keyforroom ?key-0 ?room-1)
      (locinroom ?loc-0-3 ?room-0)
      (locinroom ?loc-1-3 ?room-0)
      (moveto ?loc-0-3)
      (moveto ?loc-1-3)
      (pick ?key-0)
      (unlocked ?room-0))
    :effect (and
      (not (at ?loc-0-0))
      (not (keyat ?key-0 ?loc-0-3))
      (at ?loc-1-3)
      (unlocked ?room-1))
  )

  (:action macro0010
    :parameters (?key-0 - key ?loc-0-0 - location ?loc-0-3 - location ?loc-1-4 - location ?room-0 - room ?room-1 - room)
    :precondition (and (at ?loc-0-0)
      (keyat ?key-0 ?loc-0-3)
      (keyforroom ?key-0 ?room-1)
      (locinroom ?loc-0-3 ?room-0)
      (locinroom ?loc-1-4 ?room-1)
      (moveto ?loc-0-3)
      (moveto ?loc-1-4)
      (pick ?key-0)
      (unlocked ?room-0))
    :effect (and
      (not (at ?loc-0-0))
      (not (keyat ?key-0 ?loc-0-3))
      (at ?loc-1-4)
      (unlocked ?room-1))
  )

  (:action macro0011
    :parameters (?key-0 - key ?loc-0-0 - location ?loc-0-3 - location ?loc-1-5 - location ?room-0 - room ?room-1 - room)
    :precondition (and (at ?loc-0-0)
      (keyat ?key-0 ?loc-0-3)
      (keyforroom ?key-0 ?room-1)
      (locinroom ?loc-0-3 ?room-0)
      (locinroom ?loc-1-5 ?room-0)
      (moveto ?loc-0-3)
      (moveto ?loc-1-5)
      (pick ?key-0)
      (unlocked ?room-0))
    :effect (and
      (not (at ?loc-0-0))
      (not (keyat ?key-0 ?loc-0-3))
      (at ?loc-1-5)
      (unlocked ?room-1))
  )

  (:action macro0012
    :parameters (?key-0 - key ?loc-0-0 - location ?loc-0-3 - location ?loc-2-0 - location ?room-0 - room ?room-1 - room)
    :precondition (and (at ?loc-0-0)
      (keyat ?key-0 ?loc-0-3)
      (keyforroom ?key-0 ?room-1)
      (locinroom ?loc-0-3 ?room-0)
      (locinroom ?loc-2-0 ?room-0)
      (moveto ?loc-0-3)
      (moveto ?loc-2-0)
      (pick ?key-0)
      (unlocked ?room-0))
    :effect (and
      (not (at ?loc-0-0))
      (not (keyat ?key-0 ?loc-0-3))
      (at ?loc-2-0)
      (unlocked ?room-1))
  )

  (:action macro0013
    :parameters (?key-0 - key ?loc-0-0 - location ?loc-0-3 - location ?loc-2-1 - location ?room-0 - room ?room-1 - room)
    :precondition (and (at ?loc-0-0)
      (keyat ?key-0 ?loc-0-3)
      (keyforroom ?key-0 ?room-1)
      (locinroom ?loc-0-3 ?room-0)
      (locinroom ?loc-2-1 ?room-0)
      (moveto ?loc-0-3)
      (moveto ?loc-2-1)
      (pick ?key-0)
      (unlocked ?room-0))
    :effect (and
      (not (at ?loc-0-0))
      (not (keyat ?key-0 ?loc-0-3))
      (at ?loc-2-1)
      (unlocked ?room-1))
  )

  (:action macro0014
    :parameters (?key-0 - key ?loc-0-0 - location ?loc-0-3 - location ?loc-2-2 - location ?room-0 - room ?room-1 - room)
    :precondition (and (at ?loc-0-0)
      (keyat ?key-0 ?loc-0-3)
      (keyforroom ?key-0 ?room-1)
      (locinroom ?loc-0-3 ?room-0)
      (locinroom ?loc-2-2 ?room-0)
      (moveto ?loc-0-3)
      (moveto ?loc-2-2)
      (pick ?key-0)
      (unlocked ?room-0))
    :effect (and
      (not (at ?loc-0-0))
      (not (keyat ?key-0 ?loc-0-3))
      (at ?loc-2-2)
      (unlocked ?room-1))
  )

  (:action macro0015
    :parameters (?key-0 - key ?loc-0-0 - location ?loc-0-3 - location ?loc-2-3 - location ?room-0 - room ?room-1 - room)
    :precondition (and (at ?loc-0-0)
      (keyat ?key-0 ?loc-0-3)
      (keyforroom ?key-0 ?room-1)
      (locinroom ?loc-0-3 ?room-0)
      (locinroom ?loc-2-3 ?room-0)
      (moveto ?loc-0-3)
      (moveto ?loc-2-3)
      (pick ?key-0)
      (unlocked ?room-0))
    :effect (and
      (not (at ?loc-0-0))
      (not (keyat ?key-0 ?loc-0-3))
      (at ?loc-2-3)
      (unlocked ?room-1))
  )
)